[package]
name = "token-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
pancurses = "0.17.0"
rslint_parser = "0.3.1"
